baseURL = 'https://raahguu.dev/'
languageCode = 'en-us'
title = 'Raahguu'

# URL handling
canonifyURLs = true


[menu]
    [[menu.main]]
        name = "Writeups"
        URL = "/writeups"
        weight = 1

[module]
    [[module.mounts]]
        disableWatch = false
        source = "assets"
        target = "assets"
        [module.mounts.sites]
            [module.mounts.site.complements]
            [module.mounts.site.matrix]


[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true