baseURL = 'https://raahguu.dev/'
languageCode = 'en-us'
title = 'Raahguu'
theme = 'custom-noir'

# URL handling
relativeURLs = true
canonifyURLs = true


[menu]
    [[menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
    [[menu.main]]
        name = "Writeups"
        pageRef = "/writeups"
        weight = 2
    [[menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 3
    [[menu.main]]
        name = "Contact Me"
        pageRef = "/contact"
        weight = 4
