baseURL = 'https://raahguu.dev/'
languageCode = 'en-us'
title = 'Raahguu'

# URL handling
relativeURLs = true
canonifyURLs = true


[menu]
    [[menu.main]]
        name = "Writeups"
        URL = "/writeups"
        weight = 1
    [[menu.main]]
        name = "Contact Me"
        URL = "/contact"
        weight = 2
